version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - solairen
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - solairen